/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AED_H_RPCGEN
#define _AED_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct estado {
	char auxPalavra[100];
	char auxLetra;
	char cidadeChar[50];
	int aux1;
	int aux2;
	int aux3;
	int cidadeInt;
};
typedef struct estado estado;

struct request_vac {
	char estado[100];
	char id[100];
	char id_type;
	char status;
	int qtt_vacinas;
};
typedef struct request_vac request_vac;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define func1 1
extern  char * func1_1(estado *, CLIENT *);
extern  char * func1_1_svc(estado *, struct svc_req *);
#define func2 2
extern  char * func2_1(estado *, CLIENT *);
extern  char * func2_1_svc(estado *, struct svc_req *);
#define vezAgendar 3
extern  int * vezagendar_1(estado *, CLIENT *);
extern  int * vezagendar_1_svc(estado *, struct svc_req *);
#define qtdClientesOn 4
extern  int * qtdclienteson_1(estado *, CLIENT *);
extern  int * qtdclienteson_1_svc(estado *, struct svc_req *);
#define func4 5
extern  int * func4_1(estado *, CLIENT *);
extern  int * func4_1_svc(estado *, struct svc_req *);
#define func5 6
extern  int * func5_1(estado *, CLIENT *);
extern  int * func5_1_svc(estado *, struct svc_req *);
#define func6 7
extern  int * func6_1(estado *, CLIENT *);
extern  int * func6_1_svc(estado *, struct svc_req *);
#define funcBool 8
extern  bool_t * funcbool_1(estado *, CLIENT *);
extern  bool_t * funcbool_1_svc(estado *, struct svc_req *);
#define objeto 9
extern  estado * objeto_1(estado *, CLIENT *);
extern  estado * objeto_1_svc(estado *, struct svc_req *);
#define requisitar_vacina 10
extern  request_vac * requisitar_vacina_1(request_vac *, CLIENT *);
extern  request_vac * requisitar_vacina_1_svc(request_vac *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define func1 1
extern  char * func1_1();
extern  char * func1_1_svc();
#define func2 2
extern  char * func2_1();
extern  char * func2_1_svc();
#define vezAgendar 3
extern  int * vezagendar_1();
extern  int * vezagendar_1_svc();
#define qtdClientesOn 4
extern  int * qtdclienteson_1();
extern  int * qtdclienteson_1_svc();
#define func4 5
extern  int * func4_1();
extern  int * func4_1_svc();
#define func5 6
extern  int * func5_1();
extern  int * func5_1_svc();
#define func6 7
extern  int * func6_1();
extern  int * func6_1_svc();
#define funcBool 8
extern  bool_t * funcbool_1();
extern  bool_t * funcbool_1_svc();
#define objeto 9
extern  estado * objeto_1();
extern  estado * objeto_1_svc();
#define requisitar_vacina 10
extern  request_vac * requisitar_vacina_1();
extern  request_vac * requisitar_vacina_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_estado (XDR *, estado*);
extern  bool_t xdr_request_vac (XDR *, request_vac*);

#else /* K&R C */
extern bool_t xdr_estado ();
extern bool_t xdr_request_vac ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AED_H_RPCGEN */
