/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "aed.h"

bool_t
xdr_estado (XDR *xdrs, estado *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->auxPalavra, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->auxLetra))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->cidadeChar, 50,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->aux1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aux2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aux3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cidadeInt))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->aux1);
			IXDR_PUT_LONG(buf, objp->aux2);
			IXDR_PUT_LONG(buf, objp->aux3);
			IXDR_PUT_LONG(buf, objp->cidadeInt);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->auxPalavra, 100,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->auxLetra))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->cidadeChar, 50,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->aux1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aux2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aux3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cidadeInt))
				 return FALSE;
		} else {
			objp->aux1 = IXDR_GET_LONG(buf);
			objp->aux2 = IXDR_GET_LONG(buf);
			objp->aux3 = IXDR_GET_LONG(buf);
			objp->cidadeInt = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->auxPalavra, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->auxLetra))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cidadeChar, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aux1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aux2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aux3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cidadeInt))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_vac (XDR *xdrs, request_vac *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->estado, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->id, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->id_type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->qtt_vacinas))
		 return FALSE;
	return TRUE;
}
